blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='post_list'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('post_detail/<int:pk>', views.PostDetail.as_view(), name='post_detail'),
    path('post_create/', views.PostCreate.as_view(), name='post_create'),
    path('post_update/<int:pk>/', views.PostUpdate.as_view(), name='post_update'),
    path('post_delete/<int:pk>/', views.PostDelete.as_view(), name='post_delete')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    title = models.CharField('タイトル', max_length=32)
    text = models.TextField('本文')
    created_at = models.DateTimeField('作成日', default=timezone.now)
    updated_at = models.DateTimeField('更新日', auto_now=True)

    def __str__(self):
        return self.title

blog/forms.py
from .models import Post
from django import forms
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    """ログインフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['placeholder'] = field.label


class PostCreateForm(forms.ModelForm):
    """記事作成フォーム"""

    class Meta:
        model = Post
        fields = ('title', 'text')

blog/views.py
from django.views import generic
from .models import Post
from django.urls import reverse_lazy
from .forms import LoginForm, PostCreateForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView


class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'blog/login.html'
    success_url = reverse_lazy('blog:post_list')


class Logout(LogoutView):
    """ログアウトページ"""
    template_name = 'blog/logout.html'


class PostList(generic.ListView):
    """記事一覧ページ"""
    template_name = 'blog/post_list.html'
    model = Post
    ordering = '-updated_at'


class PostDetail(generic.DetailView):
    """記事詳細ページ"""
    template_name = 'blog/post_detail.html'
    model = Post


class PostCreate(LoginRequiredMixin, generic.CreateView):
    """記事作成ページ"""
    template_name = 'blog/post_create.html'
    model = Post
    success_url = reverse_lazy('blog:post_list')
    form_class = PostCreateForm


class PostUpdate(LoginRequiredMixin, generic.UpdateView):
    """記事編集ページ"""
    template_name = 'blog/post_create.html'
    model = Post
    form_class = PostCreateForm

    def get_success_url(self):
        return reverse_lazy('blog:post_detail', kwargs={'pk': self.kwargs.get('pk')})


class PostDelete(LoginRequiredMixin, generic.DeleteView):
    """記事削除ページ"""
    template_name = 'blog/post_delete.html'
    model = Post
    success_url = reverse_lazy('blog:post_list')

blog/templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="ja">
    <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta name="description" content="Djangoのテストの挙動を調べるプロジェクト"/>
        <meta name="keywords" content="Django test"/>
        <title>Test Blog</title>
        <link rel="stylesheet" href="{% static "css/reset.css" %}"/>
        <link rel="stylesheet" href="{% static "css/style.css" %}"/>
    </head>
    <body>
        <header class="page-header wrapper">
            <h1>
                <a href="{% url 'blog:post_list' %}" class="page-title">Blog</a>
            </h1>
            <nav class="main-nav">
                {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'blog:post_create' %}">NEW</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'blog:login' %}">Login</a>
                    </li>
                {% endif %}
            </nav>
        </header>
        {% block content %}
        {% endblock content %}
    </body>
</html>

blog/templates/blog/login.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
                {{ field }}
                {{ field.errors }}
                <hr/>
            {% endfor %}
            <button class="button" type="submit">Login</button>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/logout.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="container">
        <p>ログアウトしました</p>
    </div>
{% endblock content %}

blog/templates/blog/post_create.html
{% extends "blog/base.html" %}
{% block content %}
  <div class="container">
    <form method="post">
      {% csrf_token %}
      {{ form.non_field_errors }}
      <div class="form">{{ form.title }}</div>
      <div class="form">{{ form.text }}</div>
      <button type="submit">Send</button>
    </form>
  </div>
{% endblock content %}

blog/templates/blog/post_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <p>本当に削除しますか？</p>
            <button class="button delete-button" type="submit">Send</button>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="container">
        {% if user.is_authenticated %}
            <a class="button delete-button" href="{% url 'blog:post_delete' post.pk %}">削除</a>
        {% endif %}
        <p class="updated">{{ post.updated_at|date:'Y-m-d' }}</p>
        <h1 class="post-detail-title">
            {% if user.is_authenticated %}
                <a href="{% url 'blog:post_update' post.pk %}">{{ post.title }}</a>
            {% else %}
                {{ post.title }}
            {% endif %}
        </h1>
        <div class="post-detail-body">{{ post.text | linebreaks }}</div>
    </div>
{% endblock content %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="container">
        {% for post in post_list %}
            <article class="article">
                <p class="updated">{{ post.updated_at|date:'Y-m-d' }}</p>
                <h1 class="post-title">
                    <a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a>
                </h1>
            </article>
        {% endfor %}
    </div>
{% endblock content %}